import pygame
from game import constants, utils
BASE_W = 1920
BASE_H = 1080

SCALE_X = 1
SCALE_Y = 1

SCROLL_SPEED = 0.0
HIT_WINDOW = 60
INSTANT_LASER_OFFSET = 100
MISS_WINDOW_RATIO = 1.5
LASER_TICK_MS = 125
CURSOR_SNAP_WAIT_MS = 50
INSTANT_LASER_WAIT_MS = 30
MARGIN_MS = 10
INITIAL_WAIT_TIME_MS = 1000
AUDIO_PHASE_OFFSET_MS = 60

EDITOR_START_TIME = 0
EDITOR_BEAT_DIVISOR = "1/4"

HIT_LINE_Y = 640
LANE_WIDTH = 100
DARK_PERCENTAGE = 0.5

SIZE_XXXTINY = 5.0
SIZE_XXTINY = 10.0
SIZE_XTINY = 17.5
SIZE_TINY = 25.0
SIZE_SMALL = 50.0
SIZE_MEDIUM_TINY = 60.0     # Added this for options screen buttons
SIZE_MEDIUM_SMALL = 75.0
SIZE_MEDIUM = 100.0
SIZE_MEDIUM_LARGE = 125.0
SIZE_LARGE = 150.0
SIZE_XLARGE = 175.0
SIZE_XXLARGE = 200.0

LASER_COLOR_GREEN = "#32CD32"
LASER_COLOR_RED = "#D41D1D"
LASER_THICKNESS = 50


SELECTED_TILE = None
HIT_SOUND_PATH = "assets/skin/hit_sound.wav"
TICK_SOUND_PATH = "assets/skin/tick_sound.wav"
WHISTLE_SOUND_PATH = "assets/skin/whistle_sound.wav"

EDITOR_MAP_PATH = None
ACCURACY_POPUPS = None
COUNTDOWN_POPUPS = None

TAP_NOTE_IMAGE = None
HOLD_NOTE_HEAD_IMAGE = None
HOLD_NOTE_BODY_IMAGE = None
HOLD_NOTE_TAIL_IMAGE = None
HOLD_NOTE_HEAD_IMAGE_TINTED = None
HOLD_NOTE_BODY_IMAGE_TINTED = None
HOLD_NOTE_TAIL_IMAGE_TINTED = None
